# --- Site Settings ---
title: "ISMS Policies & Procedures"
description: "Official Information Security Management System Documentation"
url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Theme Skin ---
minimal_mistakes_skin: "contrast"

# --- Search ---
search: true

# --- Collections ---
collections:
  _engineering_policies:
    output: true
    permalink: /:collection/:path/
  _engineering_procedures:
    output: true
    permalink: /:collection/:path/
  _operational_policies:
    output: true
    permalink: /:collection/:path/
  _operational_procedures:
    output: true
    permalink: /:collection/:path/
  _access_control_policies:
    output: true
    permalink: /:collection/:path/
  _access_control_procedures:
    output: true
    permalink: /:collection/:path/
  _resilience_policies:
    output: true
    permalink: /:collection/:path/
  _resilience_procedures:
    output: true
    permalink: /:collection/:path/
  _security_policies:
    output: true
    permalink: /:collection/:path/
  _security_procedures:
    output: true
    permalink: /:collection/:path/

# --- Defaults ---
defaults:
  # _engineering Policies
  - scope:
      path: ""
      type: "_engineering_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_engineering"
  # _engineering Procedures
  - scope:
      path: ""
      type: "_engineering_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_engineering"
  # _operational Policies
  - scope:
      path: ""
      type: "_operational_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_operational"
  # _operational Procedures
  - scope:
      path: ""
      type: "_operational_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_operational"
  # _access_control Policies
  - scope:
      path: ""
      type: "_access_control_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_access_control"
  # _access_control Procedures
  - scope:
      path: ""
      type: "_access_control_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_access_control"
  # _resilience Policies
  - scope:
      path: ""
      type: "_resilience_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_resilience"
  # _resilience Procedures
  - scope:
      path: ""
      type: "_resilience_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_resilience"
  # _security Policies
  - scope:
      path: ""
      type: "_security_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_security"
  # _security Procedures
  - scope:
      path: ""
      type: "_security_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "_security"

# --- Build settings ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache