# --- Site Settings ---
title: "ISMS Policies & Procedures"
description: "ISMS Template for Health Tech Companies"
# url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Theme Skin ---
minimal_mistakes_skin: "contrast"

# --- Search ---
search: true

# --- Collections ---
collections:
  engineering_policies:
    output: true
    permalink: /:collection/:path/
  engineering_procedures:
    output: true
    permalink: /:collection/:path/
  operational_policies:
    output: true
    permalink: /:collection/:path/
  operational_procedures:
    output: true
    permalink: /:collection/:path/
  access_control_policies:
    output: true
    permalink: /:collection/:path/
  access_control_procedures:
    output: true
    permalink: /:collection/:path/
  resilience_policies:
    output: true
    permalink: /:collection/:path/
  resilience_procedures:
    output: true
    permalink: /:collection/:path/
  security_policies:
    output: true
    permalink: /:collection/:path/
  security_procedures:
    output: true
    permalink: /:collection/:path/

# --- Navigation ---
# This section defines the links that will appear in the sidebar.
# This replaces the old `_data/navigation.yml` file.
sidebar_links:
  - title: Home
    url: /
  - title: Access Control
    url: /access_control_policies/AC-POL-001
  - title: Engineering
    url: /engineering_policies/ENG-POL-001
  - title: Operational
    url: /operational_policies/OP-POL-001
  - title: Resilience
    url: /resilience_policies/RES-POL-001
  - title: Security
    url: /security_policies/SEC-POL-001


# --- Defaults ---
# This is the critical fix. We are telling Jekyll to use the 'page'
# layout for every document inside every one of your collections.
# This will override any incorrect 'layout' settings in the individual files.
defaults:
  - scope:
      type: "engineering_policies"
    values:
      layout: "page"
  - scope:
      type: "engineering_procedures"
    values:
      layout: "page"
  - scope:
      type: "operational_policies"
    values:
      layout: "page"
  - scope:
      type: "operational_procedures"
    values:
      layout: "page"
  - scope:
      type: "access_control_policies"
    values:
      layout: "page"
  - scope:
      type: "access_control_procedures"
    values:
      layout: "page"
  - scope:
      type: "resilience_policies"
    values:
      layout: "page"
  - scope:
      type: "resilience_procedures"
    values:
      layout: "page"
  - scope:
      type: "security_policies"
    values:
      layout: "page"
  - scope:
      type: "security_procedures"
    values:
      layout: "page"

# --- Build settings ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji
  - jekyll-include-cache

author:
  name   : "Sean Todd"
  avatar : "/assets/images/headshot.jpg"
  bio    : "A helpful CISO looking for his next challenge."
  links  :
    - label: "GitHub"
      url: "https://github.com/descentintomael"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/seanmtodd/"