# --- Site Settings ---
title: "ISMS Policies & Procedures"
description: "ISMS Template for Health Tech Companies"
# url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Hydejack Specific Settings ---
hydejack:
  theme: theme-base-08
  sticky_sidebar: true 
  no_page_title: true # This removes the page title from the top of each page.
  sidebar_bg_image: /assets/images/sidebar-bg2.png
  accent_image: /assets/images/sidebar-bg2.png
  invert_sidebar: true # This inverts the sidebar colors to match the theme.
  # Change the color of links and other highlighted elements.
  accent_color: rgb(128, 0, 32) # This is a dark red color.

# --- Favicon Settings ---
favicon: /assets/images/logo.png

# --- Search ---
search: true

# --- Collections ---
collections:
  engineering_policies:
    output: true
    permalink: /:collection/:path/
  engineering_procedures:
    output: true
    permalink: /:collection/:path/
  operational_policies:
    output: true
    permalink: /:collection/:path/
  operational_procedures:
    output: true
    permalink: /:collection/:path/
  access_control_policies:
    output: true
    permalink: /:collection/:path/
  access_control_procedures:
    output: true
    permalink: /:collection/:path/
  resilience_policies:
    output: true
    permalink: /:collection/:path/
  resilience_procedures:
    output: true
    permalink: /:collection/:path/
  security_policies:
    output: true
    permalink: /:collection/:path/
  security_procedures:
    output: true
    permalink: /:collection/:path/

# --- Navigation ---
# This section defines the links that will appear in the sidebar.
# This replaces the old `_data/navigation.yml` file.
sidebar_links:
  - title: Home
    url: /
  - title: Access Control
    url: /access_control_policies/AC-POL-001
  - title: Engineering
    url: /engineering_policies/ENG-POL-001
  - title: Operational
    url: /operational_policies/OP-POL-001
  - title: Resilience
    url: /resilience_policies/RES-POL-001
  - title: Security
    url: /security_policies/SEC-POL-001


# --- Defaults ---
# This is the critical fix. We are telling Jekyll to use the 'page'
# layout for every document inside every one of your collections.
# This will override any incorrect 'layout' settings in the individual files.
defaults:
  - scope:
      type: "engineering_policies"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "engineering_procedures"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "operational_policies"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "operational_procedures"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "access_control_policies"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "access_control_procedures"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "resilience_policies"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "resilience_procedures"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "security_policies"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.
  - scope:
      type: "security_procedures"
    values:
      layout: "page"
      accent_image: /assets/img/sidebar-bg2.png
      accent_color: rgb(128, 0, 32) # This is a dark red color.
      invert_sidebar: true # This inverts the sidebar colors to match the theme.

# --- Build settings ---
remote_theme: "hydecorp/hydejack@v9.2.1"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name   : "Sean Todd"
  avatar : "/assets/images/headshot.jpg"
  bio    : "A helpful CISO looking for his next challenge."
  links  :
    - label: "GitHub"
      url: "https://github.com/descentintomael"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/seanmtodd/"
  # --- Author Social Links ---
  social:
    github: open-access-policies
    email: mailto:sean@openaccesspolicies.org
    linkedin: https://www.linkedin.com/in/seanmtodd
  #   rss: true # To enable the RSS feed icon