# --- Site Settings ---
title: "ISMS Policies & Procedures"
description: "ISMS Template for Health Tech Companies"
# url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Theme Skin ---
minimal_mistakes_skin: "contrast"

# --- Search ---
search: true

# --- Navigation ---
# This section defines the links that will appear in the sidebar.
# This replaces the old `_data/navigation.yml` file.
sidebar_links:
  - title: Home
    url: /
  - title: Access Control
    url: /access_control_policies/AC-POL-001
  - title: Engineering
    url: /engineering_policies/ENG-POL-001
  - title: Operational
    url: /operational_policies/OP-POL-001
  - title: Resilience
    url: /resilience_policies/RES-POL-001
  - title: Security
    url: /security_policies/SEC-POL-001


# --- Defaults ---
# This sets default front matter values for all pages and posts.
# For Hydejack, 'page' or 'post' are the most common layouts.
defaults:
  - scope:
      path: ""
    values:
      layout: page
      # This tells all pages to use the `sidebar_links` defined above for navigation.
      sidebar:
        children: "sidebar_links"

# --- Build settings ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji
  - jekyll-include-cache

author:
  name   : "Sean Todd"
  avatar : "/assets/images/headshot.jpg"
  bio    : "A helpful CISO looking for his next challenge."
  links  :
    - label: "GitHub"
      url: "https://github.com/descentintomael"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/seanmtodd/"