# --- Site Settings ---
title: "ISMS Policies & Procedures"
description: "Official Information Security Management System Documentation"
url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Theme Skin ---
minimal_mistakes_skin: "contrast"

# --- Search ---
search: true

# --- Collections ---
collections:
  engineering_policies:
    output: true
    permalink: /:collection/:path/
  engineering_procedures:
    output: true
    permalink: /:collection/:path/
  operational_policies:
    output: true
    permalink: /:collection/:path/
  operational_procedures:
    output: true
    permalink: /:collection/:path/
  access_control_policies:
    output: true
    permalink: /:collection/:path/
  access_control_procedures:
    output: true
    permalink: /:collection/:path/
  resilience_policies:
    output: true
    permalink: /:collection/:path/
  resilience_procedures:
    output: true
    permalink: /:collection/:path/
  security_policies:
    output: true
    permalink: /:collection/:path/
  security_procedures:
    output: true
    permalink: /:collection/:path/

# --- Defaults ---
defaults:
  # _engineering Policies
  - scope:
      path: ""
      type: "engineering_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "engineering"
  # _engineering Procedures
  - scope:
      path: ""
      type: "engineering_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "engineering"
  # _operational Policies
  - scope:
      path: ""
      type: "operational_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "operational"
  # _operational Procedures
  - scope:
      path: ""
      type: "operational_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "operational"
  # _access_control Policies
  - scope:
      path: ""
      type: "access_control_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "access_control"
  # _access_control Procedures
  - scope:
      path: ""
      type: "access_control_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "access_control"
  # _resilience Policies
  - scope:
      path: ""
      type: "resilience_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "resilience"
  # _resilience Procedures
  - scope:
      path: ""
      type: "resilience_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "resilience"
  # _security Policies
  - scope:
      path: ""
      type: "security_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "security"
  # _security Procedures
  - scope:
      path: ""
      type: "security_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "security"

# --- Build settings ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache