# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.

# --- Site Settings ---
# These are used to personalize your new site.
title: "ISMS Policies and Procedures (Health Tech)"
description: "ISMS Policies and Procedures designed for a generic health tech company."
# IMPORTANT: Replace the following two lines with your site's details.
# url: "https://your-username.github.io" # e.g., "https://mmistakes.github.io"
# baseurl: "/your-repo-name" # e.g., "/minimal-mistakes"

# --- Theme Skin ---
# For a clean look, "air", "default", or "contrast" are great choices.
minimal_mistakes_skin: "air"

# --- Search ---
# Enable the search feature.
search: true

# --- Collections ---
# This is the most important part for your policies. We are telling Jekyll to
# treat each policy/procedure folder as a special group of documents.
# The folder names MUST start with an underscore (e.g., _engineering_policies).
collections:
  engineering_policies:
    output: true
    permalink: /:collection/:path/
  engineering_procedures:
    output: true
    permalink: /:collection/:path/
  operational_policies:
    output: true
    permalink: /:collection/:path/
  operational_procedures:
    output: true
    permalink: /:collection/:path/
  access_control_policies:
    output: true
    permalink: /:collection/:path/
  access_control_procedures:
    output: true
    permalink: /:collection/:path/
  resilience_policies:
    output: true
    permalink: /:collection/:path/
  resilience_procedures:
    output: true
    permalink: /:collection/:path/
  security_policies:
    output: true
    permalink: /:collection/:path/
  security_procedures:
    output: true
    permalink: /:collection/:path/

# --- Defaults ---
# This sets default front matter for all documents in a collection.
# Here, we are telling every policy to use the 'sidebar' layout and connecting
# it to the correct navigation structure from _data/navigation.yml.
defaults:
  # Engineering
  - scope:
      path: ""
      type: "engineering_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "engineering"
  - scope:
      path: ""
      type: "engineering_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "engineering"
  # Operational
  - scope:
      path: ""
      type: "operational_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "operational"
  - scope:
      path: ""
      type: "operational_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "operational"
  # Access Control
  - scope:
      path: ""
      type: "access_control_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "access_control"
  - scope:
      path: ""
      type: "access_control_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "access_control"
  # Resilience
  - scope:
      path: ""
      type: "resilience_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "resilience"
  - scope:
      path: ""
      type: "resilience_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "resilience"
  # Security
  - scope:
      path: ""
      type: "security_policies"
    values:
      layout: "sidebar"
      sidebar:
        nav: "security"
  - scope:
      path: ""
      type: "security_procedures"
    values:
      layout: "sidebar"
      sidebar:
        nav: "security"

# --- Build settings ---
# This specifies the theme and necessary plugins.
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
