# Minimal configuration for Just the Docs
theme: just-the-docs

# The title of your site
title: ISMS Policies and Procedures (Health Tech)

# A short description of your site
description: ISMS Policies and Procedures designed for a generic health tech company.

# Enable the search feature
search_enabled: true

# Logo URL
logo: "/assets/images/logo.png"